AWSTemplateFormatVersion: '2010-09-09'
Description: SQS demo
Resources:
  UserQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: user-queue
      RedrivePolicy: 
        deadLetterTargetArn: 
          Fn::GetAtt: 
            - "DeadLetterUserQueue"
            - "Arn"
        maxReceiveCount: 5 
  
  DeadLetterUserQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: user-queue-dl

  DemoSqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref UserQueue
      PolicyDocument:
        Id: "PushDocRekMessageToSQSPolicy"
        Statement:
          - Sid: "allow-sns-to-send-message-to-sqs"
            Effect: Allow
            Principal: '*'
            Action:
              - 'sqs:SendMessage'
            Resource: !GetAtt 'UserQueue.Arn'
            Condition:
              ArnEquals:
                 aws:SourceArn: !Ref 'UserQueue'